version: 1.0.{build}
image:
  - Visual Studio 2019 Preview
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      cmake_generator: "Visual Studio 16 2019"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      cmake_generator: "Unix Makefiles"

configuration:
  #- Debug
  - Release

platform:
  #- x86
  - x64

build_script:
  - mkdir build
  - cd build
  - cmd: cmake -G %cmake_generator% ..
  - cmd: cmake --build . --config %configuration%
  - sh: cmake -G $cmake_generator ..
  - sh: cmake --build . --config $configuration

test_script:
  - cmd: ctest -C %configuration% --verbose
  - cmd: ctest -C $configuration --verbose
