version: 1.0.{build}
image:
  - Visual Studio 2019 Preview
  - Ubuntu

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmd: cmake -G "Visual Studio 16 2019" ..
  - sh: cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release

test_script:
  - ctest -C Release --verbose
