version: 1.0.{build}
image: Visual Studio 2019 Preview

environment:
  matrix:
    # - compiler: clang
    - compiler: cl
    # - compiler: gcc

configuration:
  #- Debug
  - Release

platform:
  #- x86
  - x64

build_script:
  - cmake -G "Visual Studio 16 2019" ..
  - cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration% --verbose
