version: 1.0.{build}
image:
  - Visual Studio 2019 Preview
  - Ubuntu

install:
  - git submodule update --init --recursive

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
    - mkdir build & cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
    - mkdir build & cd build
    - cmake -G "Visual Studio 16 2019" ..
    - cmake --build . --config Release

test_script:
  - ctest -C Release --verbose
